apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen38-engine-benchmark-build
  namespace: llama-qwen38
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 80Gi
