apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: qwen38-codex-chat-template
    namespace: llama-qwen38
    files:
      - chat-template.jinja
resources:
  - namespace.yaml
  - pvc.yaml
  - download-job.yaml
  - download-abliterated-job.yaml
  - deployment.yaml
  - service.yaml
  - tailnet-middleware.yaml
  - strip-prefix-middleware.yaml
  - ingress.yaml
